import 'dart:math';

String getRandomFantasyName() {
  List<String> allNames = [
    "Thorne Ironheart",
    "Elara Shadowdancer",
    "Darian Stormrider",
    "Lyria Nightshade",
    "Gromm Stonefist",
    "Isolde Moonshadow",
    "Kaelin Fireforge",
    "Lirael Swiftwind",
    "Thalgrim Blackthorn",
    "Sylas Ravenshadow",
    "Aeliana Frostbloom",
    "Draven Blackthorn",
    "Seraphina Dawnstrider",
    "Grimlock Ironhide",
    "Elowen Silverleaf",
    "Thaedric Stormcaster",
    "Vaelin Shadowfang",
    "Eilif Frostbeard",
    "Isabeau Sunfire",
    "Kaelara Bloodmoon",
    "Finnian Emberforge",
    "Elowyn Whisperwind",
    "Thaddeus Ironclad",
    "Seraphina Moonshadow",
    "Dorian Frostbeard",
    "Lyria Ravenshadow",
    "Gareth Stormrider",
    "Isolde Swiftstrike",
    "Thalira Nightshade",
    "Kaelin Stonehammer",
    "Aric Blackthorn",
    "Elysia Dawnbringer",
    "Thorne Grimhammer",
    "Lirael Frostshadow",
    "Sylas Stormblade",
    "Elara Flameheart",
    "Kaelin Shadowdancer",
    "Darian Moonstrike",
    "Isolde Bloodthorn",
    "Thaddeus Ironsoul",
    "Alaric Stoneheart",
    "Elowen Windrider",
    "Soren Shadowthorn",
    "Lyria Frostwhisper",
    "Thalgrim Emberforge",
    "Isabeau Nightflame",
    "Kaelara Ironbark",
    "Seraphius Stormweaver",
    "Darian Sunblade",
    "Gwyneth Moonfire",
    "Snikkle Wartooth",
    "Gobblet Stinkfinger",
    "Razzle Quickclaw",
    "Munch Mumblegut",
    "Grizzle Snotnose",
    "Wizzle Cackletooth",
    "Snaggletooth Goblinkin",
    "Squibbly Mudfoot",
    "Nibbler Fangsnarl",
    "Fizzle Sparkfingers",
    "Father Gregorius Lightbringer",
    "Sister Seraphina Devotion",
    "Brother Cedric Faithshield",
    "High Priestess Isolde Moonblessed",
    "Deacon Thaddeus Gracewielder",
    "Acolyte Elowyn Sunspark",
    "Reverend Sylas Holyhammer",
    "Priestess Lyria Healingtouch",
    "Bishop Alaric Stormcaller",
    "Mother Elysia Dawnfaith",
    "Skeptical Samira",
    "Doubting Darian",
    "Inquisitive Irwin",
    "Critical Clara",
    "Analytical Alden",
    "Questioning Quinlan",
    "Skeptic Sage Serena",
    "Doubtful Desmond",
    "Pondering Petra",
    "Cautious Cyrus",
    "Arrogant Aegis",
    "Hubris Runelord",
    "Narcissus Stoneseeker",
    "Egoist Runemaster",
    "Vanity Glyphkeeper",
    "Prideful Runebinder",
    "Conceited Gemlord",
    "Megalomaniac Runehoarder",
    "Self-Important Rockmage",
    "Haughty Stonewarden",
    "Drakonax the Flameheart",
    "Aurelia the Shimmering",
    "Zephyrion the Windrider",
    "Obsidianax the Shadowed",
    "Ignatius the Inferno",
    "Nithriax the Frostwing",
    "Tyrothor the Thunderclaw",
    "Seraphina the Celestial",
    "Varaxalon the Earthshaker",
    "Thaladros the Timeless",
    "Snikkle Wartooth",
    "Gobblet Stinkfinger",
    "Razzle Quickclaw",
    "Munch Mumblegut",
    "Grizzle Snotnose",
    "Wizzle Cackletooth",
    "Snaggletooth Goblinkin",
    "Squibbly Mudfoot",
    "Nibbler Fangsnarl",
    "Fizzle Sparkfingers",
    "Hecate Darkmoon",
    "Morgana Shadowthorn",
    "Elara Hexenwood",
    "Branwen Moonshadow",
    "Thalindra Wyrmscar",
    "Sylas Nightshade",
    "Isolde Covenfire",
    "Grimelda Blackspell",
    "Rowan Thornbrew",
    "Elinor Spellbinder",
    "Villager Bertram",
    "Townsfolk Eliza",
    "Innkeeper Thaddeus",
    "Blacksmith Griswold",
    "Barmaid Seraphina",
    "Guard Captain Alaric",
    "Stablehand Elyse",
    "Shopkeeper Cedric",
    "Town Crier Isabella",
    "Peasant Farmer Rowan",
    "Argentos the Scalewarden",
    "Nalathrax the Voidrender",
    "Zephyros the Tempestwing",
    "Onyxia the Abyssal Queen",
    "Ignarion the Pyreheart",
    "Glacius the Rimebringer",
    "Fulgorax the Stormlord",
    "Astralastra the Cosmic",
    "Terraxius the Stonebinder",
    "Temporalis the Timekeeper"
  ];
  Random random = Random();
  return allNames[random.nextInt(allNames.length)];
}
